### PR TITLE
update: Fullstack Angular 17

### PR DESCRIPTION
**Pull request by fearlessforever**
Update: 

- DB migration
- Dashboard
- Api Server Dev Mode
- Demo : https://angular.jouningakure.com
    - username / email : hel@admin.com
    - password : 1

image

### CODE REVIEW

**Comment by andriawan** [comment]
that is a lot of work @fearlessforever. But i really appreciate the work. I just wonder, did you use it in any production project or just exploring angular for fun?

**Comment by fearlessforever** [comment]
thanks . but it's not quite done yet. for example in dashboard . i didnt finish CRUD for warteg item. for now it only reads data from database . there's no form or button to change the data in database yet. 

and yes . i do use angular in production , but only use CSR and PWA features. in this open source repo,  i'd like to explore SSR and any other angular feature in the latest version and implement any server side function in angular

**Comment by andriawan** [comment]
Interesting, i'm not quite familiar with js/ts as backend because i only do frontend as my main work. I have and idea to make this as good and stable product. In my experience, warteg as self service is quite rare. it opens possibility to explore this as Saas like POS but only focus for small warteg as MVP. What do you think @fearlessforever ?

**Comment by fearlessforever** [comment]
sure . i dont mind . but let's keep the communication and any development plans of this project in github and **most important** open source . maybe someone more experienced interested and might want to contribute as well.

i'd like to learn and explore how to contribute to github projects in a good practice ( also it might be good for my track record :smiley:  )

**Comment by andriawan** [comment]
Good. For now, i will merged this PR. Next, i will make plan for milestone v1.

In brief, for stable v1 at least we need
- fully functioning UI from selecting menu until payment
- CRUD menu, user and order
- QR code for selected order.

@fearlessforever feel free to give ideas and feedback

**Pull request merged**
